{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default use_url_translation=false() use_person=true()}
    <td class="{$sequence}">
        <span class="date"><nobr>
             {$node.object.published|l10n(date)}
        </nobr></span>
    </td>
    <td class="{$sequence}">
    <a href={$node.url_alias|ezurl}>{$node.name|wash}</a>      
    </td>
{def $person=$node.data_map.person}
    <td class="{$sequence}">{* $person.name|wash *}
      <nobr>{attribute_view_gui attribute=$node.data_map.person show_position=0 show_colon=0 link=0}</nobr>
    </td>
{*
*}
{/default}
